name: 'Setup Environment'
description: 'Setup Java and Gradle environment'
inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags'
    required: false
    default: '1'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
      shell: bash

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
      shell: bash

    - uses: gradle/actions/setup-gradle@v4
      shell: bash
